### ISSUE TITLE
Implement support for a new status ack removal command

### ISSUE THREAD

**Issue by lumagi** [seemoo-lab/pyshimmer#11]
See ShimmerResearch/shimmer3#10

**Comment by lumagi** [comment]
Great, I will probably have time to implement this tomorrow. But, unfortunately, I don't have access to a Shimmer device anymore, so I cannot test the feature myself.

**Comment by lumagi** [comment]
@qtux Would you be able to support here?

**Comment by lumagi** [comment]
@marknolan The feature should be fully implemented on #12 . I am moderately confident (I give it a 70 to 80 percent chance) to work properly. But I can't test it myself. I have been asking around to find some to test it, but it's probably not gonna happen in the near future.

**Comment by marknolan** [comment]
@lumagi if you can let me know how to test I can test with a Shimmer. Are we talking about running the example streaming code from the readme for a lengthy period of time. Docking/undocking a Shimmer in order to trigger the in-stream status response and making sure the script continues to function without error?

**Comment by lumagi** [comment]
Exactly, maybe run a Bluetooth command in a loop, such as the command to get the sampling rate. You can also subscribe to the status updates. Then place it in the dock and remove it again.

Maybe something like the following. But I wrote this without my laptop so no guarantees that there's no typos :D

```python
import time

from serial import Serial

from pyshimmer import ShimmerBluetooth, DEFAULT_BAUDRATE, DataPacket, EChannelType

def handler(*args) -> None:
    print(args)


if __name__ == '__main__':
    serial = Serial('/dev/rfcomm42', DEFAULT_BAUDRATE)
    shim_dev = ShimmerBluetooth(serial)

    shim_dev.initialize()
    shim_dev.add_status_callback(handler)

    while True:
        rate = shim_dev.get_sampling_rate()
        print(rate)
        time.sleep(1)

    shim_dev.shutdown()
```

**Comment by marknolan** [comment]
@lumagi Your code worked right out of the box. 

Crash in older LogAndStream v0.15.000:
![image](https://github.com/seemoo-lab/pyshimmer/assets/6526073/3fff198d-fe2a-4dc1-bd87-3791593ccb25)

Working with LogAndStream v0.15.004:
![image](https://github.com/seemoo-lab/pyshimmer/assets/6526073/7a3f2822-db76-4336-bdf9-fd9b0c278d42)

**Comment by lumagi** [comment]
Perfect, thanks for testing the PR!
