### ISSUE TITLE
integration with pylsl

### ISSUE THREAD

**Issue by sammy-w** [seemoo-lab/pyshimmer#13]
Hi thank you for this code. Could you explain how this could be intergrated with PyLSL to set up data streaming?
This would be a great merge with the LSL project to combine GSR with other sensors.

**Comment by lumagi** [comment]
Hi Sammy,

I took a quick look at the examples from `pylsl` and hacked something together. The code is based on the example in the main project README. I don't have access to a device, so I can't test this myself. 

```python
import time

from serial import Serial

from pylsl import StreamInfo, StreamOutlet, local_clock
from pyshimmer import ShimmerBluetooth, DEFAULT_BAUDRATE, DataPacket, EChannelType

stream_info = None
stream_outlet = None

def handler(pkt: DataPacket) -> None:
    cur_value = pkt[EChannelType.INTERNAL_ADC_13]
    outlet.push_sample(cur_value)
    print(f'Received new data point: {cur_value}')


if __name__ == '__main__':
    # Set up the pylsl stream
    stream_info = StreamInfo("shim_ppg", "PPG", 1, 512.0, "int32", "shim_uid")
    stream_outlet = StreamOutlet(info)
    
    
    
    serial = Serial('/dev/rfcomm42', DEFAULT_BAUDRATE)
    shim_dev = ShimmerBluetooth(serial)

    shim_dev.initialize()

    dev_name = shim_dev.get_device_name()
    print(f'My name is: {dev_name}')

    shim_dev.add_stream_callback(handler)

    shim_dev.start_streaming()
    time.sleep(5.0)
    shim_dev.stop_streaming()

    shim_dev.shutdown()
```

If you can help me test this, I wouldn't mind adding an example script to the repo that showcases how to connect to pylsl.

**Comment by sammy-w** [comment]
Thank you for this, I can definitely help you with testing it further on a hardware system. I have several shimmer GSR+ devices available here and I am actively working on it. 

I fixed some small errors in the code with variable names by making it consistent (e.g., info to stream_info and outlet to stream_outlet). Also '/dev/rfcomm42' didn't work for me, I changed it to "COM6" which is the incoming COM port for the Shimmer via Bluetooth. I didn't get an error message but is this correct? It works now, I can detect and record a GSR stream (stream 2) with labrecorder together with my eye-tracking stream (stream 1). However, I believe the stream now only sends one channel (PPG) and I haven't received data in the XDF file (sampling rate is 0).  

```
>>> data, header = pyxdf.load_xdf('test_GSR_multimodal.xdf') #synchronized ET and GSR data
Stream 1: Calculated effective sampling rate 187.0227 Hz is different from specified rate 60.0000 Hz.
Stream 2: Calculated effective sampling rate 0.0000 Hz is different from specified rate 512.0000 Hz.
```
Maybe I didn't specify the COM port correctly. Would you know how to fix this and add more channels (i.e., PPG, GSR data, and X, Y movement coordinates)?I am using https://github.com/labstreaminglayer/App-EyeTechDS/tree/main for collecting eye-tracking data and that seems to be working well. 

```
import time

from serial import Serial

from pylsl import StreamInfo, StreamOutlet, local_clock
from pyshimmer import ShimmerBluetooth, DEFAULT_BAUDRATE, DataPacket, EChannelType

stream_info = None
stream_outlet = None

def handler(pkt: DataPacket) -> None:
    cur_value = pkt[EChannelType.INTERNAL_ADC_13]
    stream_outlet.push_sample(cur_value)
    print(f'Received new data point: {cur_value}')


if __name__ == '__main__':
    # Set up the pylsl stream
    stream_info = StreamInfo("shim_ppg", "PPG", 1, 512.0, "int32", "shim_uid")
    stream_outlet = StreamOutlet(stream_info)
    
    serial = Serial('com6', DEFAULT_BAUDRATE)
    shim_dev = ShimmerBluetooth(serial)

    shim_dev.initialize()

    dev_name = shim_dev.get_device_name()
    print(f'My name is: {dev_name}')

    shim_dev.add_stream_callback(handler)

    shim_dev.start_streaming()
    time.sleep(5.0)
    shim_dev.stop_streaming()

    shim_dev.shutdown()
```

**Comment by sammy-w** [comment]
Didn't mean to close it sorry

**Comment by sammy-w** [comment]
didn't mean to close the issue sorry

**Comment by sammy-w** [comment]
I figured out that I should use COM5 instead (outgoing port), and I got connected to the shimmer so I got a step further.
But now I get a new error (KeyError) about handling data packets, which I think is the same as this issue https://github.com/seemoo-lab/pyshimmer/issues/1: 
```
  File "C:\Users\...\Python\Python311\Lib\site-packages\pyshimmer\bluetooth\bt_commands.py", line 64, in __getitem__
    return self._values[item]
           ~~~~~~~~~~~~^^^^^^
KeyError: <EChannelType.INTERNAL_ADC_13: 19>

it does list a number of channels under active channels including raw gsr
```
>>> print(f'Active data channels: {active_channels}')
Active data channels: [<EChannelType.TIMESTAMP: 42>, <EChannelType.ACCEL_LN_X: 1>, <EChannelType.ACCEL_LN_Y: 2>, <EChannelType.ACCEL_LN_Z: 3>, <EChannelType.VBATT: 4>, <EChannelType.GSR_RAW: 29>, <EChannelType.GYRO_MPU9150_X: 11>, <EChannelType.GYRO_MPU9150_Y: 12>, <EChannelType.GYRO_MPU9150_Z: 13>, <EChannelType.MAG_LSM303DLHC_X: 8>, <EChannelType.MAG_LSM303DLHC_Y: 9>, <EChannelType.MAG_LSM303DLHC_Z: 10>]
```
I've tried changing the data channel but I don't know how to specify the correct channel.
I've tried several things, but none of them seem seem to work:
```
def handler(pkt: DataPacket) -> None:
    cur_value = pkt[EChannelType.EXTERNAL_ADC_15]
    #cur_value = pkt[EChannelType.GSR_RAW] #(GSR channel) has to be configured in consensys that shimmer should record PPG as well
    stream_outlet.push_sample(cur_value)
    print(f'Received new data point: {cur_value}')
```
Do you know how I should proceed?

**Comment by lumagi** [comment]
> I figured out that I should use COM5 instead (outgoing port), and I got connected to the shimmer so I got a step further. But now I get a new error (KeyError) about handling data packets, which I think is the same as this issue #1:
> 
> ```
>   File "C:\Users\...\Python\Python311\Lib\site-packages\pyshimmer\bluetooth\bt_commands.py", line 64, in __getitem__
>     return self._values[item]
>            ~~~~~~~~~~~~^^^^^^
> KeyError: <EChannelType.INTERNAL_ADC_13: 19>
> ```
> 
> it does list a number of channels under active channels including raw gsr
> 
> ```
> >>> print(f'Active data channels: {active_channels}')
> Active data channels: [<EChannelType.TIMESTAMP: 42>, <EChannelType.ACCEL_LN_X: 1>, <EChannelType.ACCEL_LN_Y: 2>, <EChannelType.ACCEL_LN_Z: 3>, <EChannelType.VBATT: 4>, <EChannelType.GSR_RAW: 29>, <EChannelType.GYRO_MPU9150_X: 11>, <EChannelType.GYRO_MPU9150_Y: 12>, <EChannelType.GYRO_MPU9150_Z: 13>, <EChannelType.MAG_LSM303DLHC_X: 8>, <EChannelType.MAG_LSM303DLHC_Y: 9>, <EChannelType.MAG_LSM303DLHC_Z: 10>]
> ```
> 
> I've tried changing the data channel but I don't know how to specify the correct channel. I've tried several things, but none of them seem seem to work:

You need to enable the channels you would like to record in the `sdlog.cfg` file. Once you start streaming, all channels you enabled will be contained in the `DataPacket` you receive from the Shimmer in the callback. I just used the GSR channel as an example, but you could test the snippet with any data channel you like. The `EChannelType` class is an enum that lists all possible channels currently supported by the Shimmer. That is what the `active_channels` variable prints out, all channels the Shimmer is streaming.  If you use one of those values to access the `pkt` variable, you should get a valid sample:

```python
cur_value = pkt[EChannelType.GSR_RAW]
```

**Comment by sammy-w** [comment]
Hi, thanks for the reply. Yes I am able to connect to the device and receive data like battery status and so on. 
I managed to get it working! Indeed enabling the GSR channel in consensys is necessary. 
Another issue I ran into was that the LSL function stream_outlet.push_sample() expects a vector/list instead of an integer. 
This was solved simply by putting brackets around the GSR sample to pass it as a list of values. 

 ```
def handler(pkt: DataPacket) -> None:
    cur_value = pkt[EChannelType.GSR_RAW] #get GSR 
    #cur_value = pkt[EChannelType.ACCEL_LN_X] #send acceleration data (testing)

    #To-Do: convert Raw GSR signal to meaningful units Ohms (see shimmer doc)

    stream_outlet.push_sample([cur_value]) #push_sample requires a vector instead of a int, so I added brackets (works)
    print(f'Received new data point: {cur_value}')

```

I add the full code that I have now below. It works, but some things I'd still like to add are to functions to quit streaming with CTRL+C from CMD and an automatic cycle to find the right port instead of having to set it manually in the code. 
Also, I'd like to add a function to convert raw GSR data to meaningful units (e.g., Ohm). 
I've read the shimmer documentation on this, but it depends on the range and there is nothing specified for autorange. 
Do you know how to choose a range to specify, or how to convert the raw GSR signal to meaningful units in the autorange?
See 3.1 in: https://shimmersensing.com/wp-content/docs/support/documentation/GSR_User_Guide_rev1.13.pdf
They suggest to use range 2 or 3, so I'll just do that and ask shimmer about it. Then, I'll convert the Raw GSR signal to Ohm in the data handler function. 
```
import time
from sys import exit
from serial import Serial

from pylsl import StreamInfo, StreamOutlet, local_clock
from pyshimmer import ShimmerBluetooth, DEFAULT_BAUDRATE, DataPacket, EChannelType

stream_info = None
stream_outlet = None

def handler(pkt: DataPacket) -> None:
    cur_value = pkt[EChannelType.GSR_RAW] #get GSR 
    #cur_value = pkt[EChannelType.ACCEL_LN_X] #send acceleration data (testing)

    #To-Do: convert Raw GSR signal to meaningful units Ohms (see shimmer doc)

    stream_outlet.push_sample([cur_value]) #found the error, push_sample requires a vector instead of a int, added brackets (works)
    print(f'Received new data point: {cur_value}')

#start streaming data to LSL when someone runs "python -m ShimmerLSL" from CMD
if __name__ == '__main__':
    # Set up the pylsl stream
    stream_info = StreamInfo("shim_GSR", "GSR", 1, 51.2, "int32", "shim_uid") #send acceleration data now (testing)
    stream_outlet = StreamOutlet(stream_info)
    
    #connect to device, add: cycle through ports and find correct one
    serial = Serial('com5', DEFAULT_BAUDRATE)
    shim_dev = ShimmerBluetooth(serial)

    #add timeout, if connecting takes longer than 5 seconds exit program (give error message: wrong comport)
    shim_dev.initialize()

    dev_name = shim_dev.get_device_name()
    print(f'My name is: {dev_name}')

    shim_dev.add_stream_callback(handler)

    shim_dev.start_streaming()  #works sends acceleration data to LSL
    
    #to add: possibility to exit program from CMD with CTRL+C hotkey
    #time.sleep(5)
    #shim_dev.stop_streaming()
    #shim_dev.shutdown()

```

**Comment by lumagi** [comment]
> Hi, thanks for the reply. Yes I am able to connect to the device and receive data like battery status and so on. I managed to get it working! Indeed enabling the GSR channel in consensys is necessary. Another issue I ran into was that the LSL function stream_outlet.push_sample() expects a vector/list instead of an integer. This was solved simply by putting brackets around the GSR sample to pass it as a list of values.

Great, glad to hear the library works also on Windows!

> 
> ```
> def handler(pkt: DataPacket) -> None:
>    cur_value = pkt[EChannelType.GSR_RAW] #get GSR 
>    #cur_value = pkt[EChannelType.ACCEL_LN_X] #send acceleration data (testing)
> 
>    #To-Do: convert Raw GSR signal to meaningful units Ohms (see shimmer doc)
> 
>    stream_outlet.push_sample([cur_value]) #push_sample requires a vector instead of a int, so I added brackets (works)
>    print(f'Received new data point: {cur_value}')
> ```
> 
> I add the full code that I have now below. It works, but some things I'd still like to add are to functions to quit streaming with CTRL+C from CMD and an automatic cycle to find the right port instead of having to set it manually in the code. Also, I'd like to add a function to convert raw GSR data to meaningful units (e.g., Ohm). I've read the shimmer documentation on this, but it depends on the range and there is nothing specified for autorange. Do you know how to choose a range to specify, or how to convert the raw GSR signal to meaningful units in the autorange? See 3.1 in: https://shimmersensing.com/wp-content/docs/support/documentation/GSR_User_Guide_rev1.13.pdf They suggest to use range 2 or 3, so I'll just do that and ask shimmer about it. Then, I'll convert the Raw GSR signal to Ohm in the data handler function.

I think the documentation gives all the information you need. It has a formula to convert the raw signal to a calibrated signal. The two most-significant bits of the raw value tell you which range setting it's currently using. Then you can plug everything into the formula to get the result.

Please check if the following works and you get plausible results. If that's the case, I can add the conversion code to the library to make this easier. Or what would be even better is if you could get me some GSR Raw samples and the converted results that the Shimmer Desktop software spits out. Then I can directly test the formula.

```python
rf_values = {0: 40200.0, 1: 287000.0, 2: 1000000.0, 3: 3300000.0}

gsr_raw_w_range = pkt[EChannelType.GSR_RAW]
gsr_range = gsr_raw_w_range >> 14
gsr_raw = gsr_raw_w_range & 0x0FFF

rf = rf_values[gsr_range]
gsr = rf / ((gsr_raw * 6.0 / 4095.0) - 1)
```

**Comment by sammy-w** [comment]
Thanks yes this code seems to be working. I get GSR values in Ohm that are within the range specified by the shimmer documentation of 10 kΩ to 4.7 MΩ. E.g., Received new data point: 2698921.509886159
I add the code that I have now below: 

I needed to use a while loop to keep the program running while streaming data, it seems to work fine. 
I can collect the data in LSL and combine it with event markers and so on from other streams. 
Thank you very much for your help!

A couple small things that I would like to add are ways to automatically find the right port and maybe more channels (instead of hardcoded com5) and maybe more channels than just GSR. Any (other) thoughts or additions?
I know that it could be made into an app , see https://labstreaminglayer.org/#/
Maybe that is a nice option for this project?

```python
import time
from sys import exit
from serial import Serial

from pylsl import StreamInfo, StreamOutlet, local_clock
from pyshimmer import ShimmerBluetooth, DEFAULT_BAUDRATE, DataPacket, EChannelType

stream_info = None
stream_outlet = None

#Formula to convert raw shimmer signal to meanignful GSR values (Ohm),  depends on range see shimmer documentation
rf_values = {0: 40200.0, 1: 287000.0, 2: 1000000.0, 3: 3300000.0}

def handler(pkt: DataPacket) -> None:
    gsr_raw_w_range = pkt[EChannelType.GSR_RAW] #get raw GSR signal (AUC value)
    #cur_value = pkt[EChannelType.ACCEL_LN_X] #send acceleration data (testing)

    #Convert Raw GSR signal to meaningful GSR units Ohms (see shimmer GSR doc section 3.1)
    gsr_range = gsr_raw_w_range >> 14 #get autorange setting
    gsr_raw = gsr_raw_w_range & 0x0FFF
    rf = rf_values[gsr_range]
    gsr = rf / ((gsr_raw * 6.0 / 4095.0) - 1) #convert ADC value from sensor to Ohm
    gsr = int(gsr) #convert output value to integer for LSL

    stream_outlet.push_sample([gsr]) #push_sample requires a vector instead of a int, so added brackets (works)
    print(f'Received new data point: {gsr}')

#start streaming data to LSL when someone runs "python -m ShimmerLSL" from CMD
if __name__ == '__main__':
    # Set up the pylsl stream
    stream_info = StreamInfo("shim_GSR", "GSR", 1, 51.2, "int32", "shim_uid") #send acceleration data now (testing)
    stream_outlet = StreamOutlet(stream_info)
    
    #connect to device, add: cycle through ports and find correct one
    serial = Serial('com5', DEFAULT_BAUDRATE)
    shim_dev = ShimmerBluetooth(serial)

    #add timeout, if connecting takes longer than 5 seconds exit program (give error message: wrong comport)
    shim_dev.initialize()

    dev_name = shim_dev.get_device_name()
    print(f'My name is: {dev_name}')

    shim_dev.add_stream_callback(handler)

    shim_dev.start_streaming()  #works sends data to LSL using handler function

    #added: possibility to exit program from CMD with CTRL+C hotkey
    start = time.time()
    while True:
        time.sleep(2)
        try:
            print("working")
        except KeyboardInterrupt: #manual exit
            print("Shutdown signal received. Stopping Stream...")
            shim_dev.stop_streaming()
            print("Shutdown complete.")
            pass
```

**Comment by hcuve** [comment]
Hi @sammy-w  and @lumagi , following this thread, it seems that this API works on windows which would be great news, can I just check, that you are able to run/record multiple sensors via the API without needing Consensys Pro subscription, i.e. relying solely on the API

**Comment by sammy-w** [comment]
Hi @hcuve yes that is possible, I can confirm that the consensysPRO subscription is not necessary when using this API. 
You do need to activate the GSR signal on the device, but this can be done with the free version of consensys. 

One thing that you need to do when using multiple sensors, is defining the correct comports and devices in the script. 
The current example code above is hard-coded to work with one particular shimmer device and comport. 
It depends on your computer which one is the correct comport, this can be found in the bluetooth settings. 
This can be easily changed like so:
```
#connect to device, add: cycle through ports and find correct one
    serial = Serial('com5', DEFAULT_BAUDRATE) #instead define "com2" or "com3" etc. 
    shim_dev = ShimmerBluetooth(serial)
```
I hope this helps. 
Feel free to reach out if you have any questions

**Comment by hcuve** [comment]
Many thanks @sammy-w that's great to know, I'm aiming to run this with psychopy so it's great to know that you managed to do this on python without consensys pro and running on a windows machine. I will give it ago in the next few weeks

**Comment by hcuve** [comment]
Hello @sammy-w 

Following up on your mention of LSL in this thread, I was intrigued by the potential for real-time data visualization of sensor data https://labstreaminglayer.readthedocs.io/info/viewers.html. This would be a great to check that data quality looks fine while recording (similar to how consensys pro allows viewing live data for multiple sensors)

Have you managed to use LSL for live monitoring of sensor data during recordings? Thank you!

**Comment by sammy-w** [comment]
hi @hcuve I haven't used the labviewer myself, but that should be possible and reasonably easy to add because it functions independently from the shimmer devices. As long as you manage to start a datastream from the shimmer devices then this can be "picked up" with the lab viewer to view it over time, I believe. 

I also used to psychopy to run an experiment and send event markers from there, this can be done with another LSL datastream to send string markers that mark the end and start of events. With LSL, these event markers and GSR data will be combined and saved into one .xdf file that is synchronised over time. 

See: https://github.com/labstreaminglayer/pylsl/blob/master/pylsl/examples/SendStringMarkers.py

**Comment by hcuve** [comment]
thanks @sammy-w I will explore these, at the moment my approach with event marking on psychopy has been to store unix timestamps on psychopy itself for key events, then merge this later with the sensor data from consensys using the shimmer/consensys unix timestamps. The LSL approach sounds useful and less of a hassle, so will give it a try.
