### ISSUE TITLE
Issue using the Bluetooth API at high frequency

### ISSUE THREAD

**Issue by nathSign** [seemoo-lab/pyshimmer#18]
# Issue using the Bluetooth API at high frequency

Hello,

I have encountered an issue for the data retrieval. Currently, I am receiving a data packet of one sample each time via a callback function. The issue appears when working with frequency higher than ~30 Hz; the Shimmer buffer fills faster than the API retrieves data, leading to an offset in real-time data. More importantly, when the shimmer sensor reaches its maximum buffer capacity, it flushes, resulting in data loss.

I'm currently working on Ubuntu 22.04.4 but I have the same bug running the code on Windows. The firmware of the shimmer sensor that I'm using is 0.16.0 and my python version is 3.10.12.

I would like to use a frequency of 512 Hz but cannot go over ~30 Hz for my program to work.

Here is a zip containing a file with a main that produce the bug.
[showcase_issue.zip](https://github.com/user-attachments/files/15897746/showcase_issue.zip)
For the usage, you need to connect a shimmer3 sensor and enter the signal type used between 'ECG' and 'EDA' and the port where the shimmer is paired.

I would greatly appreciate any advice you could provide to help me resolve this issue.

Thank you.

**Comment by lumagi** [comment]
Hi,

I'm sorry to hear that you're having problems with the library. I have to say I'm surprised to hear this. How many channels are you streaming to the computer? I have been able to stream two ECG and one PPG channel at 512Hz just fine. I'm not on my computer, so I cannot check the files you attached myself.

**Comment by lumagi** [comment]
Ok, that's odd. With that many channels it shouldn't be a problem. Generally, the Python library itself is not concerned with any of the underlying Bluetooth/rfcomm stuff that could affect the bandwidth. It pulls data out of the serial interface and passes it on.

Here are some things you could check:
* How far away from the Bluetooth receiver are you?
* Do you also notice this behavior with the official Shimmer software for Windows?

**Comment by nathSign** [comment]
I'm running my code next to the shimmer with a distance of less than 50cm, and this behavior seems to only occur when using Pyshimmer. I have tried with Consensys and the Matlab API on Windows, both provided real-time data without any offset.

**Comment by nathSign** [comment]
I have programmed a script in Python that directly interacts with the Serial library, and it successfully receives data GSR and PPG at 512Hz without any issues. So, it seems that my problem only occur when using the PyShimmer library.

**Comment by lumagi** [comment]
Thanks for taking the initiative and debugging this. Could you paste your code and the commands you sent to the device? I will try to figure out what the library code is doing differently.

**Comment by lumagi** [comment]
Also, could you do some tracing by adding some print statements to the library code?

``

**Comment by lumagi** [comment]
``

**Comment by lumagi** [comment]
One more thing: did you also try running the Bluetooth example in the readme with the channels at the specified frequency? Did the error occur there as well?

**Comment by nathSign** [comment]
> One more thing: did you also try running the Bluetooth example in the readme with the channels at the specified frequency? Did the error occur there as well?

I have run the example you provided in the README, adding a counter to track if enough samples are read, and it is running well without any issues. I have got the 2.5k samples read for a 5 seconds long streaming with a frequency of 512Hz of the same channels INTERNAL_ADC_13 and GSR_RAW.

**Comment by lumagi** [comment]
Ok, then I think I know what the problem is. The ShimmerBluetooth class runs an internal thread that does all the read operations. When it detects a data packet in the stream, it pushes it out to all the callback functions that registered to receive the packets. This call is done synchronously from inside the reading thread. If any of the registered callback functions takes up too much time before returning, the thread won't be able to run at the frequency required to pull out the samples in time. Please check that you don't do anything that requires waiting or processing time inside the callback functions. If necessary, add another queue with enough buffer capacity to handle the processing in a different thread.

**Comment by nathSign** [comment]
Ok, thanks for your response. I am not sure, but I think my issue comes from the fact that I was putting the data in a queue while a thread was simultaneously checking if the queue was not empty and retrieving the data from it. This caused the queue to wait before putting the received data in because the other thread was blocking access to the queue. Without using this method, it seems to work fine. Thank you for your help !

**Comment by lumagi** [comment]
Great, glad I could help. Feel free to reopen if you experience another issue.
