### ISSUE TITLE
After successful flashing, the device returns exception.

### ISSUE THREAD

**Issue by iPsych** [seemoo-lab/pyshimmer#4]
After successful firmware flashing, and rfcomm bind,
The test code provides below error.
'device reports readiness to read but returned no data'.
Should I do something between binding and run the testcode provided in repository?

**Comment by lumagi** [comment]
Hi,
could you provide me with some more information, i.e. what Shimmer device you use, what firmware you flashed (repo, version, SDLog or LogAndStream), what code you ran, what OS you ran the code on, the exact stack trace of the error?

**Comment by lumagi** [comment]
Hi again,
are you still experiencing issues with the library? If not, please feel free to close the issue.
