### ISSUE TITLE
Realign functionality is incorrect

### ISSUE THREAD

**Issue by qtux** [seemoo-lab/pyshimmer#6]
Hi Lukas,

I think the `realign` functionality when loading data is incorrect. From my understanding it does the following right now:

1. take the first timestamp as an initial offset for the new timestamps
2. extrapolate from the first timestamp assuming a constant sampling rate while preserving the total number of observations
3. interpolate the sensor data to match the newly generated timestamps

If the original timestamps are assumed to be correct, keeping the total number of observations in the second step will lead to an too early final timestamp. Instead, the correct approach would be to impute missing timestamps and interpolate new sensor values. Otherwise, if the timestamps are assumed to be incorrect, interpolating the sensor values in the third steps is wrong.

Working with the raw data from the Shimmer devices, I have made the following observations:

- the difference between consecutive observations is almost always an integer multiple of the sample time (inverse of the sampling frequency)
- the only exception I have seen so far is the time difference between the first and second sample: often this one is not an integer multiple of the sampling time

Using this observations, my current approach is to disable the `realign` functionality, drop the first sample and impute missing values by linear interpolation as outlined below.

```python
import pandas as pd
import numpy as np
from pyshimmer import ShimmerReader, EChannelType

with open("ECG.sb3", "rb") as ecg_file:
    ecg_reader = ShimmerReader(ecg_file, realign=False)
    ecg_reader.load_file_data()
    ecg_fs = ecg_reader.sample_rate

    # convert to pandas dataframe and drop the first sample
    ecg_df = pd.DataFrame({
        "ecg1": ecg_reader[EChannelType.EXG_ADS1292R_1_CH1_24BIT][1:],
        "ecg2": ecg_reader[EChannelType.EXG_ADS1292R_1_CH2_24BIT][1:],
    }, index=ecg_reader[EChannelType.TIMESTAMP][1:])

    # add empty rows for the missing timestamps and interpolate the sensor values
    ecg_ts = pd.Index(np.arange(ecg_df.index[0], ecg_df.index[-1], 1/ecg_fs), name="timestamps")
    ecg_df = ecg_df.reindex(ecg_ts).reset_index().interpolate()
```

Concluding, I think it would be better to remove the `realign` functionality and let the users decide on how to deal with the presumably missing observations. Though, it may be helpful to raise a warning on detecting such gaps in the recording and, in particular, on detecting those which are are not an integer multiple of the sample time.

Cheers,
Matthias

**Comment by lumagi** [comment]
You are correct. I have removed the parameter and functionality from the `ShimmerReader` class.

**Comment by qtux** [comment]
Hi Lukas,

thank you, that resolves this issue.

Cheers,
Matthias
