### ISSUE TITLE
Setting which channels are streamed

### ISSUE THREAD

**Issue by dariopasquali** [seemoo-lab/pyshimmer#8]
Dear Lukas,
first thank you for this library, I have been looking for a long time for a simpler way to access the shimmer via python.
One thing is missing is the possibility to set configure the Shimmer before starting to stream.

One should be able to select which channels are active (e.g., AC13, RAW GSR, SRC, etc) and the streaming frequency.
Maybe the features is already there, if that's the case, could you please provide me a snippet on how to use it?

Thank you!
Dario

**Comment by lumagi** [comment]
I implemented commands to set the sampling rate and the active sensors. Can you please test pull requests #9 and #10 and give me feedback if they work correctly? I don't have access to a device and can't test them myself.

**Comment by lumagi** [comment]
@qtux If you find some time for the other issue, would you be willing to test these PRs as well?

**Comment by lumagi** [comment]
I will leave this issue open as reference. I merged the corresponding PRs into develop because I needed to do more complex refactoring that would lead to bigger merge conflicts. The features will need to be tested against develop.

**Comment by lumagi** [comment]
Closing this without any additional test.
